from enum import StrEnum


class UserStatus(StrEnum):
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    ACTIVE = "ACTIVE"
    BLOCKED = "BLOCKED"
    SUSPENDED = "SUSPENDED"


class UserAccountTokenPurpose(StrEnum):
    VERIFY_EMAIL = "VERIFY_EMAIL"
    RESET_PASSWORD = "RESET_PASSWORD"
    CHANGE_EMAIL = "CHANGE_EMAIL"


class MarketingConsentChannel(StrEnum):
    EMAIL = "EMAIL"
    SMS_WHATSAPP = "SMS_WHATSAPP"


class MarketingConsentStatus(StrEnum):
    GRANTED = "GRANTED"
    REVOKED = "REVOKED"
    UNKNOWN = "UNKNOWN"


class StaffIdentificationType(StrEnum):
    ECUADOR_CEDULA = "ECUADOR_CEDULA"
    PASSPORT = "PASSPORT"
    OTHER = "OTHER"


class StaffRole(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    OPERATIONS_SUPERVISOR = "OPERATIONS_SUPERVISOR"
    POINT_OPERATOR = "POINT_OPERATOR"
    DELIVERY = "DELIVERY"
    TRANSPORT_OPERATOR = "TRANSPORT_OPERATOR"
    SUPPORT = "SUPPORT"


class StaffEmploymentStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    INACTIVE = "INACTIVE"


class StaffOperationalStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    ASSIGNED = "ASSIGNED"
    IN_ROUTE = "IN_ROUTE"
    OFF_DUTY = "OFF_DUTY"


class PhoneOtpPurpose(StrEnum):
    LOGIN_OR_REGISTER = "LOGIN_OR_REGISTER"
    LINK_PHONE = "LINK_PHONE"
    CHANGE_PHONE = "CHANGE_PHONE"


class StoreStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_REVIEW = "PENDING_REVIEW"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class StoreMemberRole(StrEnum):
    OWNER = "OWNER"
    ADMINISTRATOR = "ADMINISTRATOR"
    INVENTORY_OPERATOR = "INVENTORY_OPERATOR"
    ORDER_OPERATOR = "ORDER_OPERATOR"
    FINANCE_OPERATOR = "FINANCE_OPERATOR"
    VIEWER = "VIEWER"


class StoreOnboardingStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    CORRECTIONS_REQUESTED = "CORRECTIONS_REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CONTRACT_PENDING = "CONTRACT_PENDING"
    COMPLETED = "COMPLETED"


class StoreOnboardingStage(StrEnum):
    VERIFY_DATA = "VERIFY_DATA"
    WAITING_VERIFICATION = "WAITING_VERIFICATION"
    CONTRACT_ACCEPTANCE = "CONTRACT_ACCEPTANCE"
    PRODUCTS = "PRODUCTS"


class StoreOnboardingDocumentStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class StoreVerificationDecision(StrEnum):
    PENDING = "PENDING"
    CORRECTIONS_REQUESTED = "CORRECTIONS_REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class StoreContractOtpChannel(StrEnum):
    PHONE = "PHONE"
    EMAIL = "EMAIL"


class StoreContractAcceptanceStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"


class OfferStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_REVIEW = "PENDING_REVIEW"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"


class SellerCommissionType(StrEnum):
    PERCENTAGE = "PERCENTAGE"
    FIXED = "FIXED"


class OrderStatus(StrEnum):
    PENDING_PAYMENT = "PENDING_PAYMENT"
    CONFIRMED = "CONFIRMED"
    FULFILLING = "FULFILLING"
    READY_FOR_PICKUP = "READY_FOR_PICKUP"
    COMPLETED = "COMPLETED"
    CANCELLATION_REQUESTED = "CANCELLATION_REQUESTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class SellerOrderStatus(StrEnum):
    PENDING_PAYMENT = "PENDING_PAYMENT"
    CONFIRMED = "CONFIRMED"
    PICKING = "PICKING"
    PACKED = "PACKED"
    READY_FOR_PICKUP = "READY_FOR_PICKUP"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class SellerOrderDecisionStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class SellerOrderRejectionReason(StrEnum):
    OUT_OF_STOCK = "OUT_OF_STOCK"
    DAMAGED_OR_UNSHIPPABLE = "DAMAGED_OR_UNSHIPPABLE"
    OTHER = "OTHER"


class SellerPayoutStatus(StrEnum):
    SCHEDULED = "SCHEDULED"
    PAID = "PAID"
    ON_HOLD = "ON_HOLD"
    CANCELLED = "CANCELLED"


class PaymentMethod(StrEnum):
    BANK_TRANSFER = "BANK_TRANSFER"
    CARD = "CARD"


class PaymentStatus(StrEnum):
    AWAITING_PROOF = "AWAITING_PROOF"
    PENDING_PROVIDER = "PENDING_PROVIDER"
    PROCESSING = "PROCESSING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class PaymentProofStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class PaymentProofAnalysisStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class PaymentProofPrecheckOutcome(StrEnum):
    PASSED = "PASSED"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"
    FAILED = "FAILED"


class ProductReviewStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    PUBLISHED = "PUBLISHED"
    REJECTED = "REJECTED"


class ReviewModerationOutcome(StrEnum):
    PASS = "PASS"
    FLAG = "FLAG"
    MANUAL_REQUIRED = "MANUAL_REQUIRED"


class ReviewModerationProcessingStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ReviewModerationRisk(StrEnum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ReviewModerationSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ReviewModerationMatchMode(StrEnum):
    TOKEN = "TOKEN"
    PHRASE = "PHRASE"


class ReviewModerationDecisionAction(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"


class ReviewModerationDecisionSource(StrEnum):
    AUTOMATIC = "AUTOMATIC"
    MANUAL = "MANUAL"
    LEGACY_IMPORT = "LEGACY_IMPORT"


class ReviewNotificationStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    RETRY = "RETRY"


class ProductDraftStatus(StrEnum):
    DRAFT = "DRAFT"
    INCOMPLETE = "INCOMPLETE"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    SUBMITTED = "SUBMITTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ProductDraftFileKind(StrEnum):
    IMAGE = "IMAGE"
    DOCUMENT = "DOCUMENT"


class ProductDraftFileStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DELETED = "DELETED"


class PackageStatus(StrEnum):
    CREATED = "CREATED"
    PACKED = "PACKED"
    READY_FOR_PICKUP = "READY_FOR_PICKUP"
    HANDED_OVER = "HANDED_OVER"
    CANCELLED = "CANCELLED"


class SellerInboundPackageStatus(StrEnum):
    CREATED = "CREATED"
    READY_FOR_DROPOFF = "READY_FOR_DROPOFF"
    RECEIVED_BY_ECUVEL = "RECEIVED_BY_ECUVEL"
    CANCELLED = "CANCELLED"


class LogisticsPackageStatus(StrEnum):
    AT_POINT = "AT_POINT"
    ASSIGNED = "ASSIGNED"
    IN_TRANSIT = "IN_TRANSIT"
    DEVIATED = "DEVIATED"
    DELIVERED = "DELIVERED"


class LogisticsTransferStatus(StrEnum):
    ASSIGNED = "ASSIGNED"
    IN_TRANSIT = "IN_TRANSIT"
    RECEIVED = "RECEIVED"
    DEVIATED = "DEVIATED"
    CANCELLED = "CANCELLED"


class LogisticsTrackingEventType(StrEnum):
    RECEIVED_AT_POINT = "RECEIVED_AT_POINT"
    TRANSFER_ASSIGNED = "TRANSFER_ASSIGNED"
    TRANSFER_REASSIGNED = "TRANSFER_REASSIGNED"
    PICKED_UP = "PICKED_UP"
    ARRIVAL_SCAN = "ARRIVAL_SCAN"
    RECEIVED_AT_DESTINATION = "RECEIVED_AT_DESTINATION"
    DEVIATION_DETECTED = "DEVIATION_DETECTED"
    CORRECTIVE_TRANSFER_CREATED = "CORRECTIVE_TRANSFER_CREATED"
    INCIDENT_REPORTED = "INCIDENT_REPORTED"


class LocationType(StrEnum):
    RECEIVING = "RECEIVING"
    STORAGE = "STORAGE"
    PICKING = "PICKING"
    PACKING = "PACKING"
    PICKUP_STAGING = "PICKUP_STAGING"
    QUARANTINE = "QUARANTINE"
    DAMAGED = "DAMAGED"
    RETURNS = "RETURNS"


class ReservationStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CONSUMED = "CONSUMED"
    RELEASED = "RELEASED"
    EXPIRED = "EXPIRED"


class InventoryMovementType(StrEnum):
    RECEIVE = "RECEIVE"
    PUTAWAY = "PUTAWAY"
    RESERVE = "RESERVE"
    RELEASE = "RELEASE"
    PICK = "PICK"
    PACK = "PACK"
    MOVE_IN = "MOVE_IN"
    MOVE_OUT = "MOVE_OUT"
    BLOCK = "BLOCK"
    UNBLOCK = "UNBLOCK"
    DAMAGE = "DAMAGE"
    RESTOCK = "RESTOCK"
    ADJUSTMENT_IN = "ADJUSTMENT_IN"
    ADJUSTMENT_OUT = "ADJUSTMENT_OUT"
