"""add order packages

Revision ID: 2c8bbd06a943
Revises: 3d26b6d39f3e
Create Date: 2026-06-23 05:14:50.231218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8bbd06a943'
down_revision = '3d26b6d39f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_packages',
    sa.Column('package_code', sa.String(length=40), nullable=False),
    sa.Column('barcode', sa.String(length=60), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PACKED', 'READY_FOR_PICKUP', 'HANDED_OVER', 'CANCELLED', name='package_status'), server_default='CREATED', nullable=False),
    sa.Column('packed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('packed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('packing_notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_packages_order_package_quantity_positive')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_order_packages_order_item_id_order_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['packed_by_user_id'], ['users.id'], name=op.f('fk_order_packages_packed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_packages'))
    )
    op.create_index(op.f('ix_order_packages_barcode'), 'order_packages', ['barcode'], unique=True)
    op.create_index(op.f('ix_order_packages_order_item_id'), 'order_packages', ['order_item_id'], unique=True)
    op.create_index(op.f('ix_order_packages_package_code'), 'order_packages', ['package_code'], unique=True)
    op.create_index(op.f('ix_order_packages_packed_by_user_id'), 'order_packages', ['packed_by_user_id'], unique=False)
    op.create_index(op.f('ix_order_packages_status'), 'order_packages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_packages_status'), table_name='order_packages')
    op.drop_index(op.f('ix_order_packages_packed_by_user_id'), table_name='order_packages')
    op.drop_index(op.f('ix_order_packages_package_code'), table_name='order_packages')
    op.drop_index(op.f('ix_order_packages_order_item_id'), table_name='order_packages')
    op.drop_index(op.f('ix_order_packages_barcode'), table_name='order_packages')
    op.drop_table('order_packages')
    op.execute(
        sa.text(
            'DROP TYPE IF EXISTS "package_status"'
        )
    )
    # ### end Alembic commands ###
