"""create marketplace inventory core

Revision ID: 3d26b6d39f3e
Revises: 
Create Date: 2026-06-23 00:08:45.204175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d26b6d39f3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_categories_category_sort_order_nonnegative')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_categories_code'))
    )
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('stores',
    sa.Column('public_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('tax_id', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'SUSPENDED', 'REJECTED', 'CLOSED', name='store_status'), server_default='DRAFT', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores')),
    sa.UniqueConstraint('tax_id', name=op.f('uq_stores_tax_id'))
    )
    op.create_index(op.f('ix_stores_public_code'), 'stores', ['public_code'], unique=True)
    op.create_index(op.f('ix_stores_slug'), 'stores', ['slug'], unique=True)
    op.create_index(op.f('ix_stores_status'), 'stores', ['status'], unique=False)
    op.create_table('users',
    sa.Column('public_code', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'BLOCKED', 'SUSPENDED', name='user_status'), server_default='PENDING_VERIFICATION', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_code'), 'users', ['public_code'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('warehouses',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address_line', sa.String(length=250), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), server_default='EC', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses'))
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'CONFIRMED', 'FULFILLING', 'READY_FOR_PICKUP', 'COMPLETED', 'CANCELLATION_REQUESTED', 'CANCELLED', 'EXPIRED', name='order_status'), server_default='PENDING_PAYMENT', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('shipping_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            grand_total =\n            subtotal\n            - discount_total\n            + shipping_total\n            + tax_total\n            ', name=op.f('ck_orders_order_total_consistent')),
    sa.CheckConstraint('discount_total <= subtotal', name=op.f('ck_orders_order_discount_not_greater_than_subtotal')),
    sa.CheckConstraint('discount_total >= 0', name=op.f('ck_orders_order_discount_nonnegative')),
    sa.CheckConstraint('grand_total >= 0', name=op.f('ck_orders_order_grand_total_nonnegative')),
    sa.CheckConstraint('shipping_total >= 0', name=op.f('ck_orders_order_shipping_nonnegative')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_orders_order_subtotal_nonnegative')),
    sa.CheckConstraint('tax_total >= 0', name=op.f('ck_orders_order_tax_nonnegative')),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_orders_buyer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=280), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('model_number', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('store_members',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMINISTRATOR', 'INVENTORY_OPERATOR', 'ORDER_OPERATOR', 'FINANCE_OPERATOR', 'VIEWER', name='store_member_role'), server_default='VIEWER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_store_members_store_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_store_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_members')),
    sa.UniqueConstraint('store_id', 'user_id', name='uq_store_members_store_user')
    )
    op.create_index(op.f('ix_store_members_store_id'), 'store_members', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_members_user_id'), 'store_members', ['user_id'], unique=False)
    op.create_table('warehouse_locations',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location_type', sa.Enum('RECEIVING', 'STORAGE', 'PICKING', 'PACKING', 'PICKUP_STAGING', 'QUARANTINE', 'DAMAGED', 'RETURNS', name='warehouse_location_type'), nullable=False),
    sa.Column('capacity_units', sa.Integer(), nullable=True),
    sa.Column('allows_mixed_offers', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity_units IS NULL OR capacity_units > 0', name=op.f('ck_warehouse_locations_warehouse_location_capacity_positive')),
    sa.ForeignKeyConstraint(['parent_id'], ['warehouse_locations.id'], name=op.f('fk_warehouse_locations_parent_id_warehouse_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_warehouse_locations_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_locations')),
    sa.UniqueConstraint('warehouse_id', 'code', name='uq_warehouse_locations_warehouse_code')
    )
    op.create_index(op.f('ix_warehouse_locations_barcode'), 'warehouse_locations', ['barcode'], unique=True)
    op.create_index(op.f('ix_warehouse_locations_location_type'), 'warehouse_locations', ['location_type'], unique=False)
    op.create_index(op.f('ix_warehouse_locations_parent_id'), 'warehouse_locations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_warehouse_locations_warehouse_id'), 'warehouse_locations', ['warehouse_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('catalog_sku', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=True),
    sa.Column('manufacturer_barcode', sa.String(length=80), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('height_mm IS NULL OR height_mm >= 0', name=op.f('ck_product_variants_variant_height_nonnegative')),
    sa.CheckConstraint('length_mm IS NULL OR length_mm >= 0', name=op.f('ck_product_variants_variant_length_nonnegative')),
    sa.CheckConstraint('weight_grams IS NULL OR weight_grams >= 0', name=op.f('ck_product_variants_variant_weight_nonnegative')),
    sa.CheckConstraint('width_mm IS NULL OR width_mm >= 0', name=op.f('ck_product_variants_variant_width_nonnegative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants'))
    )
    op.create_index(op.f('ix_product_variants_catalog_sku'), 'product_variants', ['catalog_sku'], unique=True)
    op.create_index(op.f('ix_product_variants_manufacturer_barcode'), 'product_variants', ['manufacturer_barcode'], unique=True)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('seller_orders',
    sa.Column('seller_order_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'CONFIRMED', 'PICKING', 'PACKED', 'READY_FOR_PICKUP', 'COMPLETED', 'CANCELLED', name='seller_order_status'), server_default='PENDING_PAYMENT', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('commission_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('seller_net_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            seller_net_total =\n            subtotal\n            - discount_total\n            - commission_total\n            ', name=op.f('ck_seller_orders_seller_order_net_consistent')),
    sa.CheckConstraint('commission_total >= 0', name=op.f('ck_seller_orders_seller_order_commission_nonnegative')),
    sa.CheckConstraint('discount_total <= subtotal', name=op.f('ck_seller_orders_seller_order_discount_valid')),
    sa.CheckConstraint('discount_total >= 0', name=op.f('ck_seller_orders_seller_order_discount_nonnegative')),
    sa.CheckConstraint('seller_net_total >= 0', name=op.f('ck_seller_orders_seller_order_net_nonnegative')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_seller_orders_seller_order_subtotal_nonnegative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_seller_orders_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_seller_orders_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seller_orders')),
    sa.UniqueConstraint('order_id', 'store_id', name='uq_seller_orders_order_store')
    )
    op.create_index(op.f('ix_seller_orders_order_id'), 'seller_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_seller_orders_seller_order_number'), 'seller_orders', ['seller_order_number'], unique=True)
    op.create_index(op.f('ix_seller_orders_status'), 'seller_orders', ['status'], unique=False)
    op.create_index(op.f('ix_seller_orders_store_id'), 'seller_orders', ['store_id'], unique=False)
    op.create_table('seller_offers',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('seller_sku', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'PAUSED', 'REJECTED', 'ARCHIVED', name='offer_status'), server_default='DRAFT', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            compare_at_price IS NULL\n            OR compare_at_price >= price\n            ', name=op.f('ck_seller_offers_seller_offer_compare_price_valid')),
    sa.CheckConstraint('commission_rate >= 0 AND commission_rate <= 100', name=op.f('ck_seller_offers_seller_offer_commission_valid')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_seller_offers_seller_offer_price_nonnegative')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_seller_offers_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_seller_offers_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seller_offers')),
    sa.UniqueConstraint('store_id', 'seller_sku', name='uq_seller_offers_store_sku'),
    sa.UniqueConstraint('store_id', 'variant_id', name='uq_seller_offers_store_variant')
    )
    op.create_index(op.f('ix_seller_offers_status'), 'seller_offers', ['status'], unique=False)
    op.create_index(op.f('ix_seller_offers_store_id'), 'seller_offers', ['store_id'], unique=False)
    op.create_index(op.f('ix_seller_offers_variant_id'), 'seller_offers', ['variant_id'], unique=False)
    op.create_table('inventory_balances',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('on_hand_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('blocked_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            reserved_quantity\n            + blocked_quantity\n            <= on_hand_quantity\n            ', name=op.f('ck_inventory_balances_inventory_allocated_not_greater_than_stock')),
    sa.CheckConstraint('blocked_quantity >= 0', name=op.f('ck_inventory_balances_inventory_blocked_nonnegative')),
    sa.CheckConstraint('on_hand_quantity >= 0', name=op.f('ck_inventory_balances_inventory_on_hand_nonnegative')),
    sa.CheckConstraint('reserved_quantity >= 0', name=op.f('ck_inventory_balances_inventory_reserved_nonnegative')),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], name=op.f('fk_inventory_balances_location_id_warehouse_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offer_id'], ['seller_offers.id'], name=op.f('fk_inventory_balances_offer_id_seller_offers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_balances')),
    sa.UniqueConstraint('offer_id', 'location_id', name='uq_inventory_balances_offer_location')
    )
    op.create_index(op.f('ix_inventory_balances_location_id'), 'inventory_balances', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_balances_offer_id'), 'inventory_balances', ['offer_id'], unique=False)
    op.create_table('order_items',
    sa.Column('seller_order_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=250), nullable=False),
    sa.Column('seller_name_snapshot', sa.String(length=150), nullable=False),
    sa.Column('seller_sku_snapshot', sa.String(length=80), nullable=False),
    sa.Column('image_url_snapshot', sa.String(length=500), nullable=True),
    sa.Column('variant_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            discount_amount <= unit_price * quantity\n            ', name=op.f('ck_order_items_order_item_discount_valid')),
    sa.CheckConstraint('\n            line_total =\n            unit_price * quantity\n            - discount_amount\n            + tax_amount\n            ', name=op.f('ck_order_items_order_item_total_consistent')),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_order_items_order_item_discount_nonnegative')),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_order_items_order_item_total_nonnegative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_order_item_quantity_positive')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_order_items_order_item_tax_nonnegative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_order_items_order_item_unit_price_nonnegative')),
    sa.ForeignKeyConstraint(['offer_id'], ['seller_offers.id'], name=op.f('fk_order_items_offer_id_seller_offers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_order_id'], ['seller_orders.id'], name=op.f('fk_order_items_seller_order_id_seller_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_offer_id'), 'order_items', ['offer_id'], unique=False)
    op.create_index(op.f('ix_order_items_seller_order_id'), 'order_items', ['seller_order_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('balance_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('RECEIVE', 'PUTAWAY', 'RESERVE', 'RELEASE', 'PICK', 'PACK', 'MOVE_IN', 'MOVE_OUT', 'BLOCK', 'UNBLOCK', 'DAMAGE', 'RESTOCK', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', name='inventory_movement_type'), nullable=False),
    sa.Column('delta_on_hand', sa.Integer(), server_default='0', nullable=False),
    sa.Column('delta_reserved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('delta_blocked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=150), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            delta_on_hand <> 0\n            OR delta_reserved <> 0\n            OR delta_blocked <> 0\n            ', name=op.f('ck_inventory_movements_inventory_movement_has_effect')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_inventory_movements_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['balance_id'], ['inventory_balances.id'], name=op.f('fk_inventory_movements_balance_id_inventory_balances'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_movements'))
    )
    op.create_index(op.f('ix_inventory_movements_actor_user_id'), 'inventory_movements', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_balance_id'), 'inventory_movements', ['balance_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_idempotency_key'), 'inventory_movements', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_reference_id'), 'inventory_movements', ['reference_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_reference_type'), 'inventory_movements', ['reference_type'], unique=False)
    op.create_table('inventory_reservations',
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('balance_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONSUMED', 'RELEASED', 'EXPIRED', name='inventory_reservation_status'), server_default='ACTIVE', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_inventory_reservations_inventory_reservation_quantity_positive')),
    sa.ForeignKeyConstraint(['balance_id'], ['inventory_balances.id'], name=op.f('fk_inventory_reservations_balance_id_inventory_balances'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_inventory_reservations_order_item_id_order_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_reservations'))
    )
    op.create_index(op.f('ix_inventory_reservations_balance_id'), 'inventory_reservations', ['balance_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_expires_at'), 'inventory_reservations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_order_item_id'), 'inventory_reservations', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_status'), 'inventory_reservations', ['status'], unique=False)
    op.create_index('uq_inventory_active_reservation', 'inventory_reservations', ['order_item_id', 'balance_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_inventory_active_reservation', table_name='inventory_reservations', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_inventory_reservations_status'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_order_item_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_expires_at'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_balance_id'), table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_index(op.f('ix_inventory_movements_reference_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_reference_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_idempotency_key'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_balance_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_actor_user_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_order_items_seller_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_offer_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_inventory_balances_offer_id'), table_name='inventory_balances')
    op.drop_index(op.f('ix_inventory_balances_location_id'), table_name='inventory_balances')
    op.drop_table('inventory_balances')
    op.drop_index(op.f('ix_seller_offers_variant_id'), table_name='seller_offers')
    op.drop_index(op.f('ix_seller_offers_store_id'), table_name='seller_offers')
    op.drop_index(op.f('ix_seller_offers_status'), table_name='seller_offers')
    op.drop_table('seller_offers')
    op.drop_index(op.f('ix_seller_orders_store_id'), table_name='seller_orders')
    op.drop_index(op.f('ix_seller_orders_status'), table_name='seller_orders')
    op.drop_index(op.f('ix_seller_orders_seller_order_number'), table_name='seller_orders')
    op.drop_index(op.f('ix_seller_orders_order_id'), table_name='seller_orders')
    op.drop_table('seller_orders')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_manufacturer_barcode'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_catalog_sku'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_warehouse_locations_warehouse_id'), table_name='warehouse_locations')
    op.drop_index(op.f('ix_warehouse_locations_parent_id'), table_name='warehouse_locations')
    op.drop_index(op.f('ix_warehouse_locations_location_type'), table_name='warehouse_locations')
    op.drop_index(op.f('ix_warehouse_locations_barcode'), table_name='warehouse_locations')
    op.drop_table('warehouse_locations')
    op.drop_index(op.f('ix_store_members_user_id'), table_name='store_members')
    op.drop_index(op.f('ix_store_members_store_id'), table_name='store_members')
    op.drop_table('store_members')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_public_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stores_status'), table_name='stores')
    op.drop_index(op.f('ix_stores_slug'), table_name='stores')
    op.drop_index(op.f('ix_stores_public_code'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_table('categories')
    enum_types = [
        "inventory_reservation_status",
        "inventory_movement_type",
        "offer_status",
        "seller_order_status",
        "warehouse_location_type",
        "store_member_role",
        "order_status",
        "user_status",
        "store_status",
    ]

    for enum_name in enum_types:
        op.execute(
            sa.text(
                f'DROP TYPE IF EXISTS "{enum_name}"'
            )
        )
    # ### end Alembic commands ###
