"""add pickup staging to order packages

Revision ID: 685add14d5a0
Revises: 2c8bbd06a943
Create Date: 2026-06-23 05:34:44.916623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685add14d5a0'
down_revision = '2c8bbd06a943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_packages', sa.Column('pickup_location_id', sa.UUID(), nullable=True))
    op.add_column('order_packages', sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_packages', sa.Column('ready_by_user_id', sa.UUID(), nullable=True))
    op.add_column('order_packages', sa.Column('ready_notes', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_order_packages_pickup_location_id'), 'order_packages', ['pickup_location_id'], unique=False)
    op.create_index(op.f('ix_order_packages_ready_by_user_id'), 'order_packages', ['ready_by_user_id'], unique=False)
    op.create_foreign_key(op.f('fk_order_packages_pickup_location_id_warehouse_locations'), 'order_packages', 'warehouse_locations', ['pickup_location_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_order_packages_ready_by_user_id_users'), 'order_packages', 'users', ['ready_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_order_packages_ready_by_user_id_users'), 'order_packages', type_='foreignkey')
    op.drop_constraint(op.f('fk_order_packages_pickup_location_id_warehouse_locations'), 'order_packages', type_='foreignkey')
    op.drop_index(op.f('ix_order_packages_ready_by_user_id'), table_name='order_packages')
    op.drop_index(op.f('ix_order_packages_pickup_location_id'), table_name='order_packages')
    op.drop_column('order_packages', 'ready_notes')
    op.drop_column('order_packages', 'ready_by_user_id')
    op.drop_column('order_packages', 'ready_at')
    op.drop_column('order_packages', 'pickup_location_id')
    # ### end Alembic commands ###
