"""add package handover fields

Revision ID: 6b84e28f5ff7
Revises: 685add14d5a0
Create Date: 2026-06-23 19:28:19.672745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b84e28f5ff7'
down_revision = '685add14d5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_packages', sa.Column('handed_over_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_packages', sa.Column('handed_over_by_user_id', sa.UUID(), nullable=True))
    op.add_column('order_packages', sa.Column('handover_notes', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_order_packages_handed_over_by_user_id'), 'order_packages', ['handed_over_by_user_id'], unique=False)
    op.create_foreign_key(op.f('fk_order_packages_handed_over_by_user_id_users'), 'order_packages', 'users', ['handed_over_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_order_packages_handed_over_by_user_id_users'), 'order_packages', type_='foreignkey')
    op.drop_index(op.f('ix_order_packages_handed_over_by_user_id'), table_name='order_packages')
    op.drop_column('order_packages', 'handover_notes')
    op.drop_column('order_packages', 'handed_over_by_user_id')
    op.drop_column('order_packages', 'handed_over_at')
    # ### end Alembic commands ###
