"""add payment attempts

Revision ID: 6dcacb1099d8
Revises: 6b84e28f5ff7
Create Date: 2026-06-24 01:59:45.899567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dcacb1099d8'
down_revision = '6b84e28f5ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_attempts',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.Enum('BANK_TRANSFER', 'CARD', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('AWAITING_PROOF', 'PENDING_PROVIDER', 'PROCESSING', 'APPROVED', 'REJECTED', 'FAILED', 'CANCELLED', 'EXPIRED', name='payment_status'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('idempotency_key', sa.String(length=150), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('provider_reference', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payment_attempts_payment_attempt_amount_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payment_attempts_order_id_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_attempts'))
    )
    op.create_index(op.f('ix_payment_attempts_idempotency_key'), 'payment_attempts', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payment_attempts_method'), 'payment_attempts', ['method'], unique=False)
    op.create_index(op.f('ix_payment_attempts_order_id'), 'payment_attempts', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_status'), 'payment_attempts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_attempts_status'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_order_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_method'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_idempotency_key'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.execute('DROP TYPE IF EXISTS "payment_status"')
    op.execute('DROP TYPE IF EXISTS "payment_method"')
    # ### end Alembic commands ###
