"""add bank transfer payment proofs

Revision ID: 71abed98a977
Revises: 6dcacb1099d8
Create Date: 2026-06-24 04:02:06.149376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71abed98a977'
down_revision = '6dcacb1099d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_proofs',
    sa.Column('payment_attempt_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=180), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'REJECTED', name='payment_proof_status'), server_default='PENDING_REVIEW', nullable=False),
    sa.Column('upload_idempotency_key', sa.String(length=150), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('review_notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_payment_proofs_payment_proof_size_positive')),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], name=op.f('fk_payment_proofs_payment_attempt_id_payment_attempts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_payment_proofs_reviewed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_payment_proofs_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_proofs'))
    )
    op.create_index(op.f('ix_payment_proofs_payment_attempt_id'), 'payment_proofs', ['payment_attempt_id'], unique=True)
    op.create_index(op.f('ix_payment_proofs_reviewed_by_user_id'), 'payment_proofs', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_payment_proofs_sha256'), 'payment_proofs', ['sha256'], unique=False)
    op.create_index(op.f('ix_payment_proofs_status'), 'payment_proofs', ['status'], unique=False)
    op.create_index(op.f('ix_payment_proofs_storage_key'), 'payment_proofs', ['storage_key'], unique=True)
    op.create_index(op.f('ix_payment_proofs_upload_idempotency_key'), 'payment_proofs', ['upload_idempotency_key'], unique=True)
    op.create_index(op.f('ix_payment_proofs_uploaded_by_user_id'), 'payment_proofs', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_proofs_uploaded_by_user_id'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_upload_idempotency_key'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_storage_key'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_status'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_sha256'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_reviewed_by_user_id'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_payment_attempt_id'), table_name='payment_proofs')
    op.drop_table('payment_proofs')
    op.execute('DROP TYPE IF EXISTS "payment_proof_status"')
    # ### end Alembic commands ###
