"""add payment proof automatic precheck

Revision ID: b1aa3259c75c
Revises: 71abed98a977
Create Date: 2026-06-24 17:32:16.074156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1aa3259c75c'
down_revision = '71abed98a977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_proof_analyses',
    sa.Column('payment_proof_id', sa.UUID(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='payment_proof_analysis_status'), server_default='PENDING', nullable=False),
    sa.Column('outcome', sa.Enum('PASSED', 'NEEDS_MANUAL_REVIEW', 'FAILED', name='payment_proof_precheck_outcome'), nullable=True),
    sa.Column('analyzer_version', sa.String(length=32), nullable=False),
    sa.Column('run_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processing_token', sa.UUID(), nullable=True),
    sa.Column('qr_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('qr_decoded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('qr_payload_sha256', sa.String(length=64), nullable=True),
    sa.Column('bank_name_detected', sa.String(length=100), nullable=True),
    sa.Column('amount_detected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transaction_at_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destination_account_suffix', sa.String(length=4), nullable=True),
    sa.Column('receipt_number_detected', sa.String(length=100), nullable=True),
    sa.Column('transaction_reference_detected', sa.String(length=150), nullable=True),
    sa.Column('ocr_mean_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ocr_word_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('amount_matches', sa.Boolean(), nullable=True),
    sa.Column('destination_account_matches', sa.Boolean(), nullable=True),
    sa.Column('date_is_plausible', sa.Boolean(), nullable=True),
    sa.Column('receipt_appears_unique', sa.Boolean(), nullable=True),
    sa.Column('qr_ocr_are_consistent', sa.Boolean(), nullable=True),
    sa.Column('bank_is_recognized', sa.Boolean(), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('failure_message', sa.String(length=500), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ocr_mean_confidence IS NULL OR (ocr_mean_confidence >= 0 AND ocr_mean_confidence <= 100)', name=op.f('ck_payment_proof_analyses_payment_proof_analysis_confidence')),
    sa.CheckConstraint('ocr_word_count >= 0', name=op.f('ck_payment_proof_analyses_payment_proof_analysis_word_count')),
    sa.CheckConstraint('run_count >= 0', name=op.f('ck_payment_proof_analyses_payment_proof_analysis_run_count')),
    sa.ForeignKeyConstraint(['payment_proof_id'], ['payment_proofs.id'], name=op.f('fk_payment_proof_analyses_payment_proof_id_payment_proofs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_proof_analyses'))
    )
    op.create_index('ix_payment_proof_analyses_bank_receipt', 'payment_proof_analyses', ['bank_name_detected', 'receipt_number_detected'], unique=False)
    op.create_index(op.f('ix_payment_proof_analyses_outcome'), 'payment_proof_analyses', ['outcome'], unique=False)
    op.create_index(op.f('ix_payment_proof_analyses_payment_proof_id'), 'payment_proof_analyses', ['payment_proof_id'], unique=True)
    op.create_index(op.f('ix_payment_proof_analyses_processing_status'), 'payment_proof_analyses', ['processing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_proof_analyses_processing_status'), table_name='payment_proof_analyses')
    op.drop_index(op.f('ix_payment_proof_analyses_payment_proof_id'), table_name='payment_proof_analyses')
    op.drop_index(op.f('ix_payment_proof_analyses_outcome'), table_name='payment_proof_analyses')
    op.drop_index('ix_payment_proof_analyses_bank_receipt', table_name='payment_proof_analyses')
    op.drop_table('payment_proof_analyses')
    op.execute('DROP TYPE IF EXISTS "payment_proof_precheck_outcome"')
    op.execute('DROP TYPE IF EXISTS "payment_proof_analysis_status"')
    # ### end Alembic commands ###
